---
# Inspired by https://github.com/rubrikinc/PowerShell-Module/blob/master/appveyor.yml
version: 1.0.0.{build}

skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

pull_requests:
  do_not_increment_build_number: true

build: off

before_build: 
  - ps: Update-ModuleManifest -ModuleVersion "$env:APPVEYOR_BUILD_VERSION" -Path "$env:APPVEYOR_BUILD_FOLDER\CygwinSetup\CygwinSetup.psd1"

before_deploy:
  - git config --global core.autocrlf false
  - git config --global core.filemode false
  - git config --global core.safecrlf false
  - git config --global user.email "lucastheisen@pastdev.com"
  - git config --global user.name "Lucas Theisen"  